#! /bin/bash

# spidev
sudo apt-get  install python3-dev -y
sudo pip install spidev

# used this lib to test pwm i2c spi gpio
sudo apt-get install python3-periphery

# to operate i2c
sudo pip install smbus2

# to operate rfid rc522
pip install mfrc522
